version: "3.7"

services:
  api-alodoutor:
    container_name: "api-alodoutor"
    image: "fbiopereira/alo-doutor:latest"
    build: 
      context: .
      dockerfile: ./AloDoutor.API/Dockerfile
    restart: "always"
    ports:
      - "4040:4040"
    environment:
      aspnetcore_environment: "Release"
      ConnectionString: "Server=localhost;Database=AloDoutor;User ID=sa;Password=P@ssw0rd;Trusted_Connection=False; TrustServerCertificate=True;MultipleActiveResultSets=True"
    networks:
      - "alo-doutor-net"

networks:
  alo-doutor-net:
    driver: bridge
