name: Build & Test 🧪

on:
  push:
    branches:
      - main
      - feature/*

env:
  DOTNET_VERSION: "7.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies 📂
        run: dotnet restore ./HealthMedScheduler.sln

      - name: Build 🧱
        run: dotnet build ./HealthMedScheduler.sln --configuration Release --no-restore

      - name: Test 🧪
        run: dotnet test ./HealthMedScheduler.sln --configuration Release --no-build
